#+TITLE: GrannyRoomba Project
#+AUTHOR: Lorenzo Flueckiger

* Goal
Develop a simple and cheap telepresence robot to improve the Skype
experience of a grandmother with her grandchild K.

* Rationale

K. does a video conference with his overseas Grand-Ma almost every
week. It is one way to keep this important relationship active. K. loves
to show in great details his latest creations (essentially Legos;-) and
they occasionally play roles.

We initially were doing Skype sessions with a laptop. We often had to move
the laptop from the table to the play area and back. Then we moved to
Skype on a smart-phone. This bring more mobility and allow to show better
details of the constructions. However it requires a person holding the
phone. Since K. needs his hands to manipulate toys, this role ends up to
Daddy. For this, we most of the time use the back camera to let the phone
holder point the camera precisely to the details of the action. This mode
is great for close up but we loose Grand-Ma' face. In addition, it is much
more demanding for the Dad than the laptop system which can stay
unattended for longer periods.

The system let Grand-Ma completely dependent of the skills of the phone
holder to keep up with the action and avoid to become dizzy. I knew that
Mobile Remote Presence (MRP) systems are designed to improve remote
interactions between people (see [[http://scholar.google.com/scholar?btnG=Search%2BScholar&as_q=%22Mobile%2BRemote%2BPresence%2BSystems%2Bfor%2BOlder%2BAdults%3A%2BAcceptance%2C%2BBenefits%2C%2Band%2BConcerns%22&as_sauthors=Beer&as_occt=any&as_epq=&as_oq=&as_eq=&as_publication=&as_ylo=&as_yhi=&as_sdtAAP=1&as_sdtp=1][Takayama HRI2011]] for a use case close to
this one) but was seeing this mostly as something on the fringe of my own
robotic domain. However when visiting our neighbor [[http://www.willowgarage.com/pages/research/human-robot-interaction][Willow Garage]] I
finally realized that I could use one of these MRP at home to have
Grand-Ma managing herself her projection into K. world!

Of course, I will not buy a nice professional MRP, but this gave me the
idea to tinker with a Roomba and an Android tablet...

* Links

